#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

COVERPROFILE="${COVERPROFILE:-coverage.out}"
COVERHTML="${COVERHTML:-coverage.html}"
COVERMODE="${COVERMODE:-atomic}"
GENERATE_HTML="${GENERATE_HTML:-1}"
GO_TEST_TAGS="${GO_TEST_TAGS:-}"
COVERPKG="${COVERPKG:-}"
GO_TEST_TARGETS="${GO_TEST_TARGETS:-}"

# Coverage scope defaults to unit-testable backend packages (exclude cmd/ and tagged tests/).
# Override with COVERAGE_SCOPE (space-separated go package patterns).
COVERAGE_SCOPE="${COVERAGE_SCOPE:-./internal/service/... ./internal/repository/... ./internal/common/... ./pkg/...}"

# Use workspace caches to avoid sandboxed paths under ~/Library/Caches.
export GOCACHE="${GOCACHE:-$ROOT_DIR/.gocache}"
mkdir -p "$GOCACHE"

if [[ -z "${GOMODCACHE:-}" ]]; then
	if [[ -d "${HOME:-}/go/pkg/mod" ]]; then
		export GOMODCACHE="${HOME}/go/pkg/mod"
	else
		export GOMODCACHE="$ROOT_DIR/.gomodcache"
		mkdir -p "$GOMODCACHE"
	fi
fi

if [[ -z "$GO_TEST_TARGETS" ]]; then
	TEST_PKGS="$(
		# Only run packages that actually have unit tests in the current build context.
		go list -f '{{if or (gt (len .TestGoFiles) 0) (gt (len .XTestGoFiles) 0)}}{{.ImportPath}}{{end}}' $COVERAGE_SCOPE \
			| sed '/^$/d' \
			| sort -u
	)"

	if [[ -z "$TEST_PKGS" ]]; then
		echo "No test packages found for COVERAGE_SCOPE: ${COVERAGE_SCOPE}" >&2
		exit 2
	fi
fi

echo "Collecting coverage into: ${COVERPROFILE}"
cmd=(go test)
if [[ -n "$GO_TEST_TAGS" ]]; then
	cmd+=(-tags "$GO_TEST_TAGS")
fi
if [[ -n "$COVERPKG" ]]; then
	cmd+=(-coverpkg "$COVERPKG")
fi
cmd+=(-covermode="$COVERMODE" -coverprofile="$COVERPROFILE")
if [[ -n "$GO_TEST_TARGETS" ]]; then
	# Space-separated go package patterns (e.g. "./...").
	cmd+=($GO_TEST_TARGETS)
else
	# Space-separated import paths generated by go list.
	cmd+=($TEST_PKGS)
fi
"${cmd[@]}"

echo
go tool cover -func="$COVERPROFILE" | tail -n 5

if [[ "$GENERATE_HTML" == "1" ]]; then
	echo "Generating HTML report: ${COVERHTML}"
	go tool cover -html="$COVERPROFILE" -o "$COVERHTML"
fi
